# Generated by Django 4.2.23 on 2025-08-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='transport_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpaymenthistory',
            name='transport_fee',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
