# Generated by Django 4.2.23 on 2025-08-13 04:28

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('master', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('marks', models.PositiveIntegerField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=lms.models.assignment_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.course')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.employee')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.coursetype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.subject')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('summary', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('status', models.CharField(choices=[('active', 'Available'), ('inactive', 'Unavailable')], default='active', max_length=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.bookcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_due_date', models.DateField()),
                ('returned', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.studentdatabase')),
            ],
        ),
        migrations.CreateModel(
            name='NewEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.studentdatabase')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_number', models.PositiveIntegerField()),
                ('exam_title', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.course')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.examtype')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.employee')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.coursetype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.subject')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStudyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('link', 'Link'), ('ebook', 'Ebook'), ('video', 'Video')], max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=lms.models.study_material_upload_path)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.course')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.employee')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.coursetype')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.assignment')),
                ('borrow_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.borrowrecord')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.newevent')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.exam')),
                ('student_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.studentfeecollection')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_userid', models.CharField(max_length=50)),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='pending', max_length=10)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.assignment')),
            ],
        ),
    ]
